type AuthPayload {
  token: String
  user: User
  error: MutationValidationError
}

input LoginInput {
  email: String!
  password: String!
}

input SignUpInput {
  name: String!
  email: String!
  password: String!
}

type Mutation {
  signup(input: SignUpInput!): AuthPayload
  login(input: LoginInput!): AuthPayload
}