type SkillType {
  id: ID!
  description: String!
  contains: [Skill!]!
}

type Skill {
  id: ID!
  description: String!
  type: SkillType!
  tradedIn: [Trade!]!
  createdAt: String!
}

input SkillTypeInput {
  description: String!
}

input SkillInput {
  description: String!
  type: ID!
}

type Query {
  skill(description: String!, page: PageInfo!): [Skill!]!
  skillType(id: ID!): SkillType
}

type Mutation {
  createSkillType(input: SkillTypeInput!): SkillType!
  createSkill(input: SkillInput!): Skill!
}