# import Skill from "Skill.gql"
# import User from "User.gql"

type Trade {
    id: ID!
    user: User!
    skill: Skill!
    other: Trade!
    scheduledFor: DateTime
    createdAt: DateTime!
    updatedAt: DateTime!
}